homework.lambda.part3.exercise1 (yakushenko)
elefus/epam-lab-java8-2018-09 pull request #100
Opened 2018-09-29 20:04 UTC by Dgafar

2018-09-30 22:17 UTC, TarasKobzar approved these changes

2018-09-30 22:17 UTC, TarasKobzar commented on src/test/java/lambda/part3/exercise1/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = (p) -> stringLengthExtractor.apply(fullNameExtractor.apply(personExtractor.apply(p)));
Also, you can use the "andThen" method instead of the "apply" method. I'm sure you know it )

2018-10-01 06:32 UTC, vkovrovEPAM commented
Please resolve conflicts and follow Taras's suggestions

2018-10-01 06:32 UTC, vkovrovEPAM requested changes
Please resolve conflicts and follow Taras's suggestions

2018-10-31 10:49 UTC, merged