homework.lambda.part3.exercise1 (kornaushenkov)
elefus/epam-lab-java8-2018-09 pull request #115
Opened 2018-09-30 13:28 UTC by EugeneGrim

2018-09-30 13:37 UTC, Lopat commented on src/test/java/lambda/part3/exercise1/Exercise1.java
> +        return employee.getPerson();
нужно сделать функции по типу 
Function<Employee, Person> func = employee -> employee.getPerson();
и скомбинировать функции через and в fullNameExtractror

2018-09-30 13:50 UTC, EugeneGrim commented on src/test/java/lambda/part3/exercise1/Exercise1.java
> +        return employee.getPerson();
Fixed

2018-09-30 17:19 UTC, Lopat approved these changes

2018-10-01 06:25 UTC, vkovrovEPAM requested changes

2018-10-01 06:25 UTC, vkovrovEPAM commented on src/test/java/lambda/part3/exercise1/Exercise1.java
> +            .apply(employee);
It is better to use ` personExtractor.andThen(fullNameExtractor).andThen(stringLengthExtractor)` here without `employee ->` and whithout `.apply(employee)`

2018-10-01 11:31 UTC, EugeneGrim commented on src/test/java/lambda/part3/exercise1/Exercise1.java
> +            .apply(employee);
Fixed

2018-10-01 13:10 UTC, vkovrovEPAM approved these changes

2018-10-03 15:21 UTC, merged