KOVROV: Exercise 3 [kovrov]
elefus/epam-lab-java8-2018-09 pull request #28
Opened 2018-09-23 09:34 UTC by vkovrovEPAM

2018-09-23 11:23 UTC, TarasKobzar approved these changes
Название Николай просил давать как имя ветки + (фамилия):
homework.lambda.part1.exercise3 (kovrov)

2018-09-23 19:24 UTC, lesscau approved these changes

2018-09-25 10:19 UTC, elefus requested changes
Please fix branch name

2018-09-25 12:03 UTC, vkovrovEPAM commented
@elefus done

2018-09-26 07:20 UTC, merged