homework.lambda.part2.exercise2 (kobzar)
elefus/epam-lab-java8-2018-09 pull request #29
Opened 2018-09-23 11:01 UTC by TarasKobzar

Complete.

2018-09-23 14:32 UTC, AlexMem requested changes

2018-09-23 14:32 UTC, AlexMem commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("Николай", "", 30)), is(true));
Didn't you think that smth is wrong here and your predicate implemetation isn't apply to it's name?

2018-09-23 21:34 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("Николай", "", 30)), is(true));
Нет. Я так не думаю. "Request changes" ставить не желательно. Николай про это говорил. Особенно, если просто вопрос. Т.к. когда другие люди одобрят, то все равно это не сможет смержиться, пока висит "User request changes". Снимите, пожалуйста. Замечания, а тем более вопросы, пишем через функцию "Comment".

2018-09-24 10:12 UTC, Lopat approved these changes

2018-09-24 11:07 UTC, Ilya21 commented
you need to check original repository. @elefus has updated this exercise

2018-09-24 15:03 UTC, vkovrovEPAM requested changes

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> validate = person -> !person.getFirstName().isEmpty() && !person.getLastName().isEmpty();
check for null first and last name

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("Николай", "", 30)), is(true));
It is the right way of review, your tests are not correct, one above and one below, it should check for false

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
can get NulPointerException here

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("", "Мельников", 20)), is(true));
Two tests above should check for false, so if your tests pass something wrong here

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
Check first and last name for null

2018-09-24 15:03 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("", "Мельников", 20)), is(true));
same about tests as above

2018-09-24 16:19 UTC, TarasKobzar commented
@Ilya21 спасибо что сказал, что Николай изменил первоначальный вариант тестов. Подсказал хоть )

2018-09-24 18:57 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> validate = person -> !person.getFirstName().isEmpty() && !person.getLastName().isEmpty();
Спорный момент. Не считаю, что тут надо делать проверку на нал. Я лично хочу увидеть налпоинтер, если у меня вместо фамилии или имени будет нал стоять. А у тебя с такой проверкой, если будет нал вместо имени, ни чего не произойдет, просто тест не пройдет. И будешь искать, в чем дело. Это намного хуже.

2018-09-24 19:00 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
И буду рад, если у меня вместо имени будет нал стоять! ) Подробнее ответил выше.

2018-09-24 19:01 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
Ответ такой же, как и выше )

2018-09-24 19:03 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        assertThat(personHasNotEmptyLastNameAndFirstName.test(new Person("Николай", "", 30)), is(true));
@AlexMem выяснилось почему так. Закачал новые тесты.

2018-09-24 19:32 UTC, AlexMem approved these changes

2018-09-24 19:37 UTC, TarasKobzar commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> validate = person -> !person.getFirstName().isEmpty() && !person.getLastName().isEmpty();
То, что ты предпочитаешь иметь незафиксированный нал, ни как не "Request changes". Чтобы выразить свою точку зрения, есть категория "Comment".

2018-09-26 07:18 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> validate = person -> !person.getFirstName().isEmpty() && !person.getLastName().isEmpty();
Действительно, нет однозначного решения - все зависит от способов объявления и использования свойств.
В каких-то случаях значение `null` не допустимо - тогда лучше сразу выбросить `NPE`, чтобы локализовать ситуацию. В других же - отсутствие значения может быть допустимым, исходя из специфики предметной области и `null` становится валидным значением. Однако, в таком случае можно подумать над использованием `Optional`.

2018-09-26 07:19 UTC, merged