homework.lambda.part2.exercise2 (vertiletskii)
elefus/epam-lab-java8-2018-09 pull request #40
Opened 2018-09-23 17:56 UTC by Ilya21

2018-09-23 19:12 UTC, AlexMem approved these changes

2018-09-24 14:57 UTC, vkovrovEPAM requested changes

2018-09-24 14:57 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> validate = (p1) -> !(p1.getFirstName().isEmpty() || p1.getLastName().isEmpty());
Why not use &&, it would be easier to understand for others, and u can get NullPointerException if not check firstname and lastname for null

2018-09-24 14:57 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
check for null

2018-09-24 14:57 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
check for null

2018-09-24 14:57 UTC, vkovrovEPAM commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        Predicate<Person> personHasEmptyLastName = person -> person.getLastName().isEmpty();
same

2018-09-24 20:32 UTC, TarasKobzar approved these changes

2018-09-25 09:42 UTC, Ilya21 commented
@vkovrovEPAM please check solution with handled null

2018-09-25 11:59 UTC, vkovrovEPAM approved these changes

2018-09-26 07:13 UTC, merged